
rule all:
    input:
        'detk_report/detk_report.html'

rule gunzip:
    input:
        '{path}.gz'
    output:
        temp('{path}')
    shell:
        'gunzip -c {input} > {output}'

rule stats:
    input:
        counts='all_mRNA_nonzero_{type}_counts_trim.csv',
        info='sample_info.csv'
    output:
        temp('{type}_summary_stats.csv')
    shell:
        'detk-stats summary --log {input.counts} -o {output} --column-data={input.info}'

rule filter:
    input:
        'all_mRNA_nonzero_{type}_counts_trim.csv'
    output:
        temp('{type}_filtered.csv')
    shell:
        'detk-filter "mean(all) > 10" -o {output} {input}'

rule generate:
    input:
        'raw_summary_stats.csv',
        'norm_summary_stats.csv',
        'norm_filtered.csv'
    output:
        'detk_report/detk_report.html'
    shell:
        'detk-report generate'
