
rule all:
    input:
        'detk_report/detk_report.html'

rule gunzip:
    input:
        '{path}.gz'
    output:
        temp('{path}')
    shell:
        'gunzip -c {input} > {output}'

rule stats:
    input:
        'all_mRNA_nonzero_raw_counts_trim.csv'
    output:
        temp('summary_stats.csv')
    shell:
        'detk-stats summary {input} -o {output}'

rule generate:
    input:
        rules.stats.output[0]
    output:
        'detk_report/detk_report.html'
    shell:
        'detk-report generate --dev'
